# Generated by Django 2.2.5 on 2019-12-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10, verbose_name='Источник')),
                ('time', models.CharField(blank=True, max_length=15, verbose_name='Время')),
                ('status_valid', models.CharField(blank=True, max_length=1, verbose_name='Статус')),
                ('latitude', models.CharField(blank=True, max_length=30, verbose_name='Широта')),
                ('n_s', models.CharField(blank=True, max_length=1, verbose_name='Для широты')),
                ('longitude', models.CharField(blank=True, max_length=10, verbose_name='Долгота')),
                ('e_w', models.CharField(blank=True, max_length=1, verbose_name='Для долготы')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Скорость')),
                ('path_agele', models.CharField(blank=True, max_length=15, verbose_name='Путевой угол')),
                ('date', models.CharField(blank=True, max_length=6, verbose_name='Дата')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Магнитное склонение')),
                ('direction_magnetic_declination', models.CharField(blank=True, max_length=1, null=True, verbose_name='Направление магнитного склонения')),
                ('mode', models.CharField(blank=True, max_length=1, verbose_name='Направление магнитного склонения')),
                ('checksum', models.CharField(blank=True, max_length=1, verbose_name='Направление магнитного склонения')),
            ],
            options={
                'verbose_name': 'csv_view_on_web',
            },
        ),
    ]
